### ISSUE TITLE
Directional typing

### ISSUE THREAD

**Issue by m-ender** [SirBogman/hexagony.net#3]
The absolute killer feature for this IDE would be if it were possible to just type out linear sections of code in any direction. This is roughly how I imagine this working:

- The cursor has a direction associated with. This could probably use the same little wedge icon that's used for IP directions, but in black/white (depending on dark mode setting).
- Have buttons and maybe keyboard shortcuts to change the direction.
- Typing a character generally advances the cursor in the current direction after typing, applying edge wrapping if necessary.
- Typing a space advances the cursor without changing the current character.
- Backspace deletes the current character and moves the cursor backwards. (Or maybe it shouldn't even delete the character, so that there's an easy ways to move the cursor forwards and backwards along its current direction without affecting the grid.)
- Del deletes the current character without moving the cursor.
- Typing a mirror automatically adjusts the cursor position.
- Not entirely sure how to deal with branches (either `<>` or grid corners). I would say either default to positive, or have a toggle somewhere that indicates whether to follow positive or negative branches.

There's probably some weird edge cases where this behaviour doesn't *quite* do what you expect, but I think in the majority of use cases this would feel very natural and intuitive for typing code into the grid.

**Comment by SirBogman** [comment]
When editing the current cell while running the typing direction would be initialized by the current execution direction.

Ideally, but not necessarily, this would be done while execution is paused.

**Comment by SirBogman** [comment]
When moving backwards, branches aren't ambiguous. But It is ambiguous when moving backwards through a corner in the direction of the corner, because two paths lead there. I the use has just moved forward through that corner, that information could potentially be stored to help decide which path to move through when going backwards.

**Comment by m-ender** [comment]
How about: backspace moves you to the negative edge, shift or ctrl+backspace moves you to the positive edge. Gives the user access to both paths without requiring any fancy logic for keeping track of where they came from.

**Comment by SirBogman** [comment]
I think I prefer tab and shift+tab for navigating forward and backwards on the typing axis. Space could also navigate forwards if you want. I would like backspace to delete text as you move backwards.

**Comment by m-ender** [comment]
Oh yeah, of course. Tab and/or space (+shift) for moving along the typing axis makes a lot of sense.

**Comment by SirBogman** [comment]
The only thing missing at this point is a way to set the typing direction with buttons. It would be particularly useful on mobile.

**Comment by SirBogman** [comment]
Stepping back over `$` is currently a bit weird. It skips the `$` itself. Perhaps when navigating backwards, it should be treated like a noop?

Typing `[` sends the cursor to the default location of IP 5. Typing `]` or `#` sends the cursor to the default location of IP 1. This seems reasonable enough, but the behavior could be modified so that these characters don't affect navigation, if desired.

**Comment by m-ender** [comment]
Yeah, I think `[]#` should probably do nothing special for directional typing. This default behaviour is going to be helpful exactly once per program, and afterwards is probably going to be a bit annoying. For `$`, ignoring it when stepping backwards seems reasonable.

**Comment by SirBogman** [comment]
I suppose for `$` the most correct thing to do is to skip the instruction immediately following it when stepping backwards. This would allow you to walk backward in the same way you walked forward, even when a mirror follows the `$`.

The logic would be something like the following. When moving backwards, first assume the preceding instruction is a no-op and take another step in the same direction. If we arrive at a `$`, then stay there. Otherwise, simulate the execution of the preceding instruction as normal.

**Comment by SirBogman** [comment]
The above suggestion wouldn't work correctly for two `$` in a row. I think it would be necessary to keep navigating backwards while encountering `$` in order to count them, then determine what to do based on the count. I can't just save the movement history, because the use may navigate backwards without ever having navigated forwards.

**Comment by m-ender** [comment]
I'm not sure trying to skip stuff while navigating backwards is desirable. If you reach a `$/` while going backwards, it's just as likely that you were planning to move back through the mirror instead of the `$`, so I think not skipping is the less confusing behaviour.

**Comment by SirBogman** [comment]
Works for me. It's also simpler and I hadn't started implementing it yet.
